apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    manifests:
      - ./infra/k8s/*

build:
  artifacts:
    - image: utkarsh852/userservice
      context: userService
      docker:
        dockerfile: Dockerfile
  
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.json'
            dest: .
          - src: 'src/**/*.env'
            dest: .
          - src: 'src/**/*.yml'
            dest: .
          - src: 'src/**/*.yaml'
            dest: .